### ISSUE TITLE
Provide a page for discussions

### ISSUE THREAD

**Issue by crehn** [crehn/DesignType#12]

**Comment by MattSkyJumper** [comment]
Added a comment functionality on pages: dimensions, types and personal result. Seems to work.

**Comment by crehn** [comment]
How about the "learn more" page?

**Comment by MattSkyJumper** [comment]
currently it is only the entry page. Ups and there is also a "still work in progress" hint we should remove...
In my eyes it depends on us. If we want to have only concrete discussions about dimensions and types it currently fits. If we also like to have a discussion about the whole thing (instead or in parallel to the xing group) we should add the comment function there as well. 
Mabye we should talk about again about a "discussion concept". What do we want to discuss and with which medium and where.
