### ISSUE TITLE
Result graphs in personal result page

### ISSUE THREAD

**Issue by crehn** [crehn/DesignType#13]

**Comment by crehn** [comment]
I think we are almost finished here. The one thing which is missing is that the type overlap chart should have a link including the ukey. This is no problem but then the type overlap graph is wrong. We should show the graph but without the overlap in such a case. In order to do so the data from the server has to contain the correct type so it can be compared to the type given via query parameter.

**Comment by crehn** [comment]
@MattSkyJumper :
The main purpose of the type overlap chart is that it should show that there is some uncertainty concerning the resulting design type. If there is a 3:2 divide in one dimension (e.g. 3 simple, 2 powerful), we are actually quite uncertain about our categorization. I guess there is a large group of people who will fit better with the other type.

In my eyes the chart should reflect that uncertainty as much as possible. This means that the overlapped area of the "second best match" should give the impression "oh this type is almost as likely as the one shown to me now."

Have a look at the [current state of the chart](http://design-types.net/test/result.html?type=PCPR&ukey=55a28eed81800). The test data set shows pragmatic to idealistic is 3:2. PCPR is thus only slightly more likely than PCIR. The actual uncertainty is somewhat 60:40. If we'd like to cover that mathematically correctly 66% of the area of PCIR should be covered. Unfortunately the quadrangle covers only around 25%.

For that reason I changed the overlap polygon to an octogon. This at least showed the relation a bit better.

In c8f9dd9 you reverted the type overlap chart such that the area is a quadrangle again. I guess that means you like the quadrangle better. But maybe we can find a way to show a bit more coverage and to reflect the uncertainty better.

In fact I'd like a splotch or cloud like shape with blurry borders best but that's quite complicated to produce.

**Comment by MattSkyJumper** [comment]
I just changed to 1/3 and 2/3 points. IMHO enough for me. We can optimze again with #48

**Comment by crehn** [comment]
Please push your changes, so I can review them.
