### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by crehn** [crehn/DesignType#15]

**Comment by crehn** [comment]
A favicon needs to be nice-looking and rememberable. Sorry, but I think this one fails in both categories.

**Comment by MattSkyJumper** [comment]
For me working for the moment. Can optimize it after #33

**Comment by crehn** [comment]
I will create another favicon.

**Comment by MattSkyJumper** [comment]
I think it fails only in the first category - it is definitely rememberable...
If you have something that matches both: go ahead.

**Comment by MattSkyJumper** [comment]
you think the new one is better? I would say: partially. The shape is better but e.g. the crown is too weak and nearly not recognizable. 
I think the whole heraldic topic is very good but will need a few loops till it's finished.

**Comment by crehn** [comment]
Definitely better. It's also not necessary to recognize the crown as a crown. You just have to recognize that "this is the design-types favicon". It can be completely abstract; as long as it's recognizable as a whole and nice to look at, it's good.

If you don't like the crown in the favicon, we can remove it, tough. No problem with that.

**Comment by MattSkyJumper** [comment]
hm - I think your current one is also just a temporarily one until we really have the whole heraldic stuff final. I see two possibilities:
1) use any temporarily
2) wait until the final favicon is available

For case one: would it be a compromise to use something else instead. I mean not mine, not yours but e.g. only the polygon of the other graph without the squares in the background? Such a polygon also matches to typical questionaire results or feedbacks like the one from our Business Academy.
![polygon](https://cloud.githubusercontent.com/assets/7963918/9066614/fa701e9a-3ad8-11e5-87e6-46d23cf6d398.png)

**Comment by MattSkyJumper** [comment]
mean something like this:
![polygon1](https://cloud.githubusercontent.com/assets/7963918/9069702/15c0a2de-3aeb-11e5-9841-a81f34ae4727.png)

**Comment by MattSkyJumper** [comment]
another variant:
![question_mark](https://cloud.githubusercontent.com/assets/7963918/9070679/51f01ac2-3af1-11e5-977c-06f21dbbb019.png)
by the way: I should all 3 icons to my wife (without saying which was mine). Her comments were: the one with the polygon is "unscheinbar", the one with the shield one cannot see or recognize the crown, the one with the bars is recognizable because of the colors. After asking which fits to a questionaire she also meant: the one with the bars because the bars look like text passages.

The new one I build keeps the main color from the jumbotron and just contains a question mark because we ask something...

**Comment by MattSkyJumper** [comment]
and after thinking a bit more... new ones maybe get confused when they see the website but do not know the link to the heraldic until they finished the questionaire. From this perspective I would prefer having an independent one...

**Comment by crehn** [comment]
If our idea with the certificates works out, people coming to our website will know the coats of arms already. We could also create a page logo and place if prominently on the start page. An early sketch of this is already in the repo (same file).

The question mark is OK, tough. I'm fine with using it.
