### ISSUE TITLE
Assess Colleagues: Specific questionaire

### ISSUE THREAD

**Issue by crehn** [crehn/DesignType#2]

**Comment by Matt78** [comment]
new page with contents for assess colleagues available in the wiki. I typically used 5 Statements for each direction of a dimension. Currently only "Pragmatic" and "Idealistic" just have 4. 
Feel free to add one and to review the others.

**Comment by crehn** [comment]
I've just revisited the questions again. For now I'm quite happy with them. You might wanna have a look at [my changes](https://github.com/crehn/DesignType/wiki/Assess-Colleagues/_compare/3455557128f00544207efce13d9c7c6d9c5e7356...dab270e822b36a24cefc385f30f6e98d9bf3cd63).

**Comment by crehn** [comment]
Done. There are separate questionnaires now and the statements are located in separate files. Still needs some testing but should work.

**Comment by crehn** [comment]
From my side everything seems to work. We can close this issue as soon as you are satisfied with the statements.

**Comment by Matt78** [comment]
I just changed two statements we already talked about. Rest of your changes focused on commas. Though both ways are possible I like mine more - it has less commas and is closer to german.
For rest of these details we can do changes in code and close this issue.

**Comment by crehn** [comment]
I'm not completely happy with your revert but we can discuss that some other time. For now I'll just fix the grammar mistake.
