### ISSUE TITLE
PAIT coat of arms is wrong

### ISSUE THREAD

**Issue by MattSkyJumper** [crehn/DesignType#74]
we changed from "The Professor" to "The Scientist". This has already been finished for all text occurences but NOT in the result picture.

**Comment by MattSkyJumper** [comment]
see here: http://design-types.net/test/result.html?type=PAIT&ukey=5828c20245df3

**Comment by crehn** [comment]
It's already done: https://github.com/crehn/DesignType/blob/master/img/types/PAIT.png

It's just not on the test stage.
